package ai.mindconnect.filestore;


import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Optional;

/**
 * Stores uploaded files by id inside a tenant. Ids are generated by the store,
 * never derived from names, so uploads cannot collide or traverse.
 */
public interface FileStore {

    /** Stores {@code content} under a fresh id and returns its metadata. */
    StoredFile save(String name, String contentType, InputStream content) throws IOException;

    Optional<StoredFile> find(FileId id);

    /** The stored bytes; the caller closes the stream. */
    InputStream content(FileId id) throws IOException;

    /** Every file, newest first. */
    List<StoredFile> list();

    /** Removes the file and its metadata; a missing id is not an error. */
    void delete(FileId id) throws IOException;
}
