package ai.mindconnect.filestore;


import ai.mindconnect.agent.UserId;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Optional;

/**
 * Stores uploaded files by id inside a tenant. Ids are generated by the store,
 * never derived from names, so uploads cannot collide or traverse.
 */
public interface FileStore {

    /** Stores {@code content} under a fresh id, on nobody's behalf, and returns its metadata. */
    default StoredFile save(String name, String contentType, InputStream content) throws IOException {
        return save(name, contentType, content, null);
    }

    /**
     * Stores {@code content} under a fresh id and returns its metadata.
     *
     * @param creator the user the file is stored for, recorded as its
     *                {@link StoredFile#creator()}; {@code null} for nobody
     */
    StoredFile save(String name, String contentType, InputStream content, UserId creator) throws IOException;

    Optional<StoredFile> find(FileId id);

    /** The stored bytes; the caller closes the stream. */
    InputStream content(FileId id) throws IOException;

    /** Every file, newest first. */
    List<StoredFile> list();

    /** Removes the file and its metadata; a missing id is not an error. */
    void delete(FileId id) throws IOException;
}
