package ai.mindconnect.workflow.ui.diagram;

import ai.mindconnect.ui.ext.diagram.UiDiagram;
import ai.mindconnect.ui.ext.diagram.UiDiagramEdge;
import ai.mindconnect.ui.ext.diagram.UiDiagramNode;
import ai.mindconnect.workflow.domain.BlockData;
import ai.mindconnect.workflow.domain.CodeData;
import ai.mindconnect.workflow.domain.ForEachData;
import ai.mindconnect.workflow.domain.HttpCallData;
import ai.mindconnect.workflow.domain.IfData;
import ai.mindconnect.workflow.domain.WorkflowData;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Smoke tests for {@link WorkflowDiagramBuilder}. With the children-based
 * container model, the diagram is a tree rather than a flat list: branch
 * containers, loop containers, and block containers hold their nested
 * steps as {@link UiDiagramNode#getChildren()}. Tests use
 * {@link #flatten(UiDiagram)} to walk the whole tree when checking total
 * counts, and assert directly on the tree shape when the nesting is the
 * thing under test.
 */
class WorkflowDiagramBuilderTest {

    private final WorkflowDiagramBuilder builder = new WorkflowDiagramBuilder();

    // -----------------------------------------------------------------------
    // Linear workflow — no containers in play
    // -----------------------------------------------------------------------

    @Test
    void linearWorkflowProducesStartActionEnd() {
        WorkflowData wf = new WorkflowData();
        wf.setName("greet");
        CodeData step = new CodeData();
        step.setName("hello");
        step.setCode("'hello'");
        wf.addSteps(step);

        UiDiagram d = builder.build(wf);

        // Linear flow: every node lives at top level (no containers).
        assertThat(d.getNodes()).hasSize(3);   // start + action + end
        assertThat(d.getEdges()).hasSize(2);   // start→action, action→end

        UiDiagramNode start  = nodeByClass(d, WorkflowShapes.CLASS_EVENT_START);
        UiDiagramNode end    = nodeByClass(d, WorkflowShapes.CLASS_EVENT_END);
        UiDiagramNode action = nodeByClass(d, WorkflowShapes.CLASS_ACTION);

        assertThat(start.isSynthetic()).isTrue();
        assertThat(end.isSynthetic()).isTrue();
        // Start/end carry reserved stepRefs so the editor can persist their
        // drag-positions through the regular LayoutStore path.
        assertThat(start.getStepRef()).isEqualTo(WorkflowDiagramBuilder.SYNTHETIC_START_REF);
        assertThat(end.getStepRef()).isEqualTo(WorkflowDiagramBuilder.SYNTHETIC_END_REF);
        assertThat(action.isSynthetic()).isFalse();
        assertThat(action.getStepRef()).isEqualTo("hello");
        assertThat(action.getData()).containsEntry("stepType", "code");
    }

    @Test
    void blankStepNameGetsAutoGeneratedAndPersistedBackOnWorkflow() {
        WorkflowData wf = new WorkflowData();
        CodeData a = new CodeData();
        CodeData b = new CodeData();
        wf.addSteps(a, b);

        UiDiagram d = builder.build(wf);

        assertThat(a.getName()).isEqualTo("step_1");
        assertThat(b.getName()).isEqualTo("step_2");
        assertThat(flatten(d))
            .filteredOn(n -> !n.isSynthetic())
            .extracting(UiDiagramNode::getStepRef)
            .containsExactly("step_1", "step_2");
    }

    @Test
    void duplicateUserSuppliedNamesFailLoudly() {
        WorkflowData wf = new WorkflowData();
        CodeData a = new CodeData(); a.setName("shared");
        CodeData b = new CodeData(); b.setName("shared");
        wf.addSteps(a, b);

        assertThatThrownBy(() -> builder.build(wf))
            .isInstanceOf(DuplicateStepNameException.class)
            .hasMessageContaining("shared");
    }

    @Test
    void autoNamesDontCollideAcrossBuildsAfterInsertion() {
        // First build: a single blank step gets named step_1.
        WorkflowData wf = new WorkflowData();
        CodeData first = new CodeData();
        wf.addSteps(first);
        builder.build(wf);
        assertThat(first.getName()).isEqualTo("step_1");

        // Second build with another blank step inserted. The previous step
        // still carries step_1, so the new one must become step_2 — not
        // collide on step_1 like the naive counter-resets-every-build code
        // used to do.
        CodeData second = new CodeData();
        wf.addSteps(second);
        builder.build(wf);
        assertThat(second.getName()).isEqualTo("step_2");

        // Third build, same logic — step_3.
        CodeData third = new CodeData();
        wf.addSteps(third);
        builder.build(wf);
        assertThat(third.getName()).isEqualTo("step_3");
    }

    @Test
    void autoNamingSkipsUserSuppliedStepNumbers() {
        // If the user manually named a step "step_5", the next blank step
        // should jump to step_6 rather than re-issue step_1 (which then
        // would advance past step_5 only by walking — risking collisions
        // along the way if multiple steps were auto-named in a single build).
        WorkflowData wf = new WorkflowData();
        CodeData manual = new CodeData(); manual.setName("step_5");
        CodeData blank  = new CodeData();
        wf.addSteps(manual, blank);

        builder.build(wf);
        assertThat(blank.getName()).isEqualTo("step_6");
    }

    // -----------------------------------------------------------------------
    // If / Decision — branch containers
    // -----------------------------------------------------------------------

    @Test
    void ifStepEmitsDecisionBranchContainersAndMerge() {
        WorkflowData wf = new WorkflowData();

        CodeData yes = new CodeData(); yes.setName("yes-step");
        BlockData then = new BlockData(); then.addSteps(yes);

        CodeData no = new CodeData(); no.setName("no-step");
        BlockData els = new BlockData(); els.addSteps(no);

        IfData ifStep = new IfData();
        ifStep.setName("branch");
        IfData.Condition cond = new IfData.Condition();
        cond.setCondition("x > 0");
        cond.setThenBlock(then);
        ifStep.setConditions(cond);
        ifStep.setElseBlock(els);

        wf.addSteps(ifStep);

        UiDiagram d = builder.build(wf);

        // Top-level: start, decision, then-container, else-container, a
        // synthetic merge gateway, end. The merge is the BPMN-style join
        // diamond that gathers every branch's tail back onto the trunk.
        assertThat(d.getNodes())
            .extracting(UiDiagramNode::getShapeClass)
            .containsExactlyInAnyOrder(
                WorkflowShapes.CLASS_EVENT_START,
                WorkflowShapes.CLASS_DECISION,
                WorkflowShapes.CLASS_BRANCH_CONTAINER,   // then
                WorkflowShapes.CLASS_BRANCH_CONTAINER,   // else
                WorkflowShapes.CLASS_MERGE,              // synthetic join
                WorkflowShapes.CLASS_EVENT_END);
        assertThat(d.getNodes())
            .anyMatch(n -> WorkflowShapes.CLASS_MERGE.equals(n.getShapeClass()));

        // Each branch container still wraps its single action step.
        for (UiDiagramNode branch : d.getNodes().stream()
                .filter(n -> WorkflowShapes.CLASS_BRANCH_CONTAINER.equals(n.getShapeClass()))
                .toList()) {
            assertThat(branch.getChildren()).hasSize(1);
            assertThat(branch.getChildren().get(0).getShapeClass())
                .isEqualTo(WorkflowShapes.CLASS_ACTION);
        }

        // Structural edges: decision → then-container (label "x > 0"),
        // decision → else-container (label "else"). Both branch containers
        // feed the synthetic merge via plain flow edges (label null), and
        // the merge feeds the end marker.
        UiDiagramNode mergeNode = nodeByClass(d, WorkflowShapes.CLASS_MERGE);
        UiDiagramNode endNode = nodeByClass(d, WorkflowShapes.CLASS_EVENT_END);
        assertThat(d.getEdges())
            .filteredOn(e -> e.getKind() == UiDiagramEdge.Kind.STRUCTURAL)
            .extracting(UiDiagramEdge::getLabel)
            .containsExactlyInAnyOrder("x > 0", "else");
        // Both branch containers flow into the merge gateway.
        assertThat(d.getEdges())
            .filteredOn(e -> mergeNode.getId().equals(e.getTarget()))
            .hasSize(2);
        // The merge gateway flows on to the end marker.
        assertThat(d.getEdges())
            .filteredOn(e -> mergeNode.getId().equals(e.getSource())
                          && endNode.getId().equals(e.getTarget()))
            .hasSize(1);

        assertThat(flatten(d)).hasSize(8);  // top-6 + 2 children
    }

    @Test
    void ifWithoutElseDrawsImplicitElseEdgeStraightToNextStep() {
        WorkflowData wf = new WorkflowData();
        CodeData yes = new CodeData(); yes.setName("yes");
        BlockData then = new BlockData(); then.addSteps(yes);

        IfData ifStep = new IfData();
        ifStep.setName("branch");
        IfData.Condition cond = new IfData.Condition();
        cond.setCondition("x > 0");
        cond.setThenBlock(then);
        ifStep.setConditions(cond);
        // No else-block set on purpose.

        wf.addSteps(ifStep);

        UiDiagram d = builder.build(wf);

        // A synthetic merge gateway gathers the branches back onto the trunk.
        assertThat(d.getNodes())
            .anyMatch(n -> WorkflowShapes.CLASS_MERGE.equals(n.getShapeClass()));

        // With no else-block defined, the "no condition matched" path is drawn
        // as an implicit-else structural edge that bypasses the branches and
        // goes straight from the decision to the merge, labelled "else" so the
        // user can see what happens when nothing fires.
        UiDiagramNode decision = nodeByClass(d, WorkflowShapes.CLASS_DECISION);
        UiDiagramNode mergeNode = nodeByClass(d, WorkflowShapes.CLASS_MERGE);
        assertThat(d.getEdges())
            .filteredOn(e -> e.getKind() == UiDiagramEdge.Kind.STRUCTURAL
                          && decision.getId().equals(e.getSource())
                          && mergeNode.getId().equals(e.getTarget()))
            .extracting(UiDiagramEdge::getLabel)
            .containsExactly("else");
    }

    // -----------------------------------------------------------------------
    // ForEach — loop container holds body steps
    // -----------------------------------------------------------------------

    @Test
    void parallelForEachRendersAsLoopContainer() {
        WorkflowData wf = new WorkflowData();
        ForEachData fe = new ForEachData();
        fe.setName("loop");
        fe.setLoopOver("items");
        fe.setRunVar("item");
        fe.setParallel(true);
        // Loop body has one step so we can verify nesting.
        CodeData body = new CodeData(); body.setName("body-step");
        fe.addSteps(body);
        wf.addSteps(fe);

        UiDiagram d = builder.build(wf);

        // Top-level node classes. Both parallel and sequential iterations
        // render the same way — the parallel flag is purely runtime
        // semantics, so there is no fork/join scaffolding, just the loop
        // container on the trunk between start and end.
        assertThat(d.getNodes())
            .extracting(UiDiagramNode::getShapeClass)
            .containsExactlyInAnyOrder(
                WorkflowShapes.CLASS_EVENT_START,
                WorkflowShapes.CLASS_LOOP_CONTAINER,
                WorkflowShapes.CLASS_EVENT_END);

        // Loop body step lives as a child of the loop container.
        UiDiagramNode loop = nodeByClass(d, WorkflowShapes.CLASS_LOOP_CONTAINER);
        assertThat(loop.getChildren()).hasSize(1);
        assertThat(loop.getChildren().get(0).getStepRef()).isEqualTo("body-step");
        assertThat(loop.getStepRef()).isEqualTo("loop");
    }

    @Test
    void sequentialForEachIsASingleContainer() {
        WorkflowData wf = new WorkflowData();
        ForEachData fe = new ForEachData();
        fe.setName("loop");
        fe.setLoopOver("items");
        fe.setRunVar("item");
        fe.setParallel(false);
        wf.addSteps(fe);

        UiDiagram d = builder.build(wf);

        assertThat(d.getNodes())
            .filteredOn(n -> !n.isSynthetic())
            .extracting(UiDiagramNode::getShapeClass)
            .containsExactly(WorkflowShapes.CLASS_LOOP_CONTAINER);
    }

    // -----------------------------------------------------------------------
    // HttpCall — exercise the multi-line label
    // -----------------------------------------------------------------------

    @Test
    void httpCallLabelIncludesMethodAndUrl() {
        WorkflowData wf = new WorkflowData();
        HttpCallData http = new HttpCallData();
        http.setName("fetch");
        http.setMethod("POST");
        http.setUrl("https://example.com/api/widgets");
        wf.addSteps(http);

        UiDiagram d = builder.build(wf);

        UiDiagramNode action = nodeByClass(d, WorkflowShapes.CLASS_ACTION);
        assertThat(action.getLabel()).contains("fetch", "POST", "https://example.com");
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    /** Flattens the diagram tree into a single list (depth-first). */
    private List<UiDiagramNode> flatten(UiDiagram d) {
        var out = new ArrayList<UiDiagramNode>();
        for (UiDiagramNode n : d.getNodes()) collectTree(n, out);
        return out;
    }

    private void collectTree(UiDiagramNode n, List<UiDiagramNode> out) {
        out.add(n);
        if (n.getChildren() != null) {
            for (UiDiagramNode c : n.getChildren()) collectTree(c, out);
        }
    }

    /** Finds the (first) node with the given shapeClass anywhere in the tree. */
    private UiDiagramNode nodeByClass(UiDiagram d, String shapeClass) {
        return flatten(d).stream()
            .filter(n -> shapeClass.equals(n.getShapeClass()))
            .findFirst()
            .orElseThrow(() -> new AssertionError("No node with shapeClass " + shapeClass));
    }
}
